import {StyleSheet} from 'react-native';
import { RotationGestureHandler } from 'react-native-gesture-handler';

export default StyleSheet.create({
    container:{
        flex:1,
        justifyContent:"center",
        backgroundColor:"white",
        marginTop:50,
        borderTopLeftRadius:80,
    },
    main:{
        flexDirection:"row",
        marginLeft:40,
        marginRight:40,
        backgroundColor:"white",
        marginTop:50,
    },
    shopName1:{
        fontWeight:"bold",
        textAlign:"center",
        fontSize:40,
        marginLeft:-80,
        marginTop:10,
    },
    shopName2:{
        fontSize:40,
        textAlign:"center",
        fontFamily:"sans-serif",
        marginRight:120,
    },
    image:{
        height:70,
        width:70,
        resizeMode:"cover",
        borderTopRightRadius:20,
        borderBottomRightRadius:20,
        borderBottomLeftRadius:20,
    },
    card:{
        flex:1,
        flexDirection:"row",
        borderBottomLeftRadius:20,
        backgroundColor:"white",
        marginTop:-45
    },
    nameInfo:{
        flex:1,
        marginRight:13
    },
    nameText:{
        fontWeight:"bold",
        fontSize:14,
        marginLeft:15,
    },
    infoText:{
        fontFamily:"sans-serif-light",
        fontSize:11,
        marginLeft:15,
        flexWrap:"wrap"
    },
    backImage:{
        flex:1,
        resizeMode:"cover",
    },
    button:{
        height:50,
        width:300,
        justifyContent:"center",
        backgroundColor:"#2b13af",
        borderRadius:10,
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20,
        marginLeft:28
    },
    buttonText:{
        color:'white',
        fontSize:20,
        fontWeight:"bold"
    },
    options:{
        flex:1,
        flexDirection:"row",
        alignItems:"center",
        marginTop:20,
    },
    searchIcon:{
        marginLeft:42,
        position:"absolute",
        color:"#7e839d",
        fontSize:17
    },
    searchBox:{
        marginHorizontal:38,
        color:"#7e839d",
    },
    searchText:{
        color:"#7e839d",
        marginLeft:-35,
        marginRight:12
    },
    icon:{
        marginHorizontal:165,
        transform:[{rotateZ:'90deg'}],
        color:"#a2a5b8",
    },
    plusBox:{
        color:"#dd491e",
        height:40,
        marginLeft:46,
        height:28,
        width:27,
        fontSize:26,
        marginTop:1
    },
    plusIcon:{
        marginLeft:46,
        color:"#2b13af",
        position:"absolute",
    },
    priceText:{
        marginLeft:10,
        color:"#fe844b",
        marginTop:33,
    },
    title:{
        flexDirection:'row',
    },
    view1:{
        flexDirection:'row',
        marginLeft:100,
        marginRight:100,
        flexDirection:'row',
    },
    txt:{
        fontWeight:"bold",
    },
    cardStyle:{
        height:50,
        width:100
    }
})